spring.application.name=developer-directory-api

spring.datasource.url=jdbc:postgresql://localhost:5332/devdirectory
spring.datasource.username=devuser
spring.datasource.password=devpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
